### PR TITLE
Refactor OS Build System

### LINKED ISSUE #23: Use built-in 'xz' post-processor
Packer now offers built-in support for xz format archives. It is possible to archive without using external script and tool 'pixz' for this. 

Here is example snippet for generating a archive which is directly flashable using etcher. 

```
  post-processor "compress" {
    output  = "{{.BuildName}}.xz"
    compression_level   = 9
    keep_input_artifact = false
  }

```

### LINKED ISSUE #24: Use built-in checksum post-processor
Packer offers built-in support for generating various checksum. There is no need to use external tools (such `sha256sum`) for this in the post-processing step.

```
post-processor "checksum" {
  checksum_types = ["sha1", "sha256"]
  output = "{{.BuildName}}_{{.ChecksumType}}.checksum"
  }

```

### LINKED ISSUE #25: Remove Raspberry Pi OS Support
Update raspberry pi 11 script to use the latest release of raspberry pi.

### PR DESCRIPTION
**Pull request by arky**
Multiple tasks to update the Pi Rogue OS.

- Remove Raspberry Pi Support (Fixes #25 Fixes #26) 
- Remove Post.sh with custom post processors (Fixes #23 , Fixes #24) 
- Update .gitignore to ignore intermediator build files

### CODE REVIEW

**Comment by CyrilBrulebois** [comment]
Hi @arky,

Keeping in mind I'm not at all familiar with Packer, I'm a bit surprised to see some hardcoded checksum (both before and after your changes). Since the checksum is available on https://raspi.debian.net/ (by adding `.sha256` to the image URL), any chance that it could be downloaded on the fly instead of being hardcoded and requiring an update every time the tested image is updated?

**Comment by arky** [comment]
@CyrilBrulebois That is how it was coded in this project. I could enhance the refactor to dynamically fetch checksum file, however there seems to some bugs in that functionality. So I left it as it is.  

https://github.com/hashicorp/packer-plugin-qemu/issues/155

**Comment by arky** [comment]
@CyrilBrulebois I have added the functionality to dynamically fetch checksum file as you advised.

**Comment by U039b** [comment]
Thank you @arky!
Did you managed to check if the final image is valid (not corrupted, etc.)?

**Comment by arky** [comment]
@U039b Flashed and tested on Raspberry Pi (Model B Revision 2.0) without any issues. If the output is corrupt, the most likely issue might be the compress level setting.

**Comment by U039b** [comment]
It looks good to me. Thank you very much @arky :tada:

**Pull request merged**
